# Generated by Django 5.2.13 on 2026-04-29 19:23

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WindowDoorDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(help_text='Design name/label', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('design_type', models.CharField(choices=[('sliding_window', 'Sliding Window'), ('casement_window', 'Casement Window'), ('fixed_window', 'Fixed Window'), ('sliding_door', 'Sliding Door'), ('casement_door', 'Casement Door'), ('french_door', 'French Door'), ('bi_fold_door', 'Bi-fold Door'), ('tilt_turn', 'Tilt & Turn')], max_length=20)),
                ('width_mm', models.IntegerField(help_text='Width in millimeters')),
                ('height_mm', models.IntegerField(help_text='Height in millimeters')),
                ('num_panels', models.IntegerField(default=2, help_text='Number of panels/leaves')),
                ('glass_type', models.CharField(choices=[('clear_float', 'Clear Float'), ('tinted', 'Tinted'), ('frosted', 'Frosted'), ('tempered', 'Tempered'), ('double_glazed', 'Double Glazed'), ('laminated', 'Laminated'), ('reflective', 'Reflective')], default='clear_float', max_length=20)),
                ('glass_thickness_mm', models.IntegerField(default=5)),
                ('frame_material', models.CharField(choices=[('upvc', 'uPVC'), ('aluminium_standard', 'Aluminium (Standard)'), ('aluminium_thermal_break', 'Aluminium (Thermal Break)'), ('wood_composite', 'Wood Composite')], default='upvc', max_length=30)),
                ('finish', models.CharField(choices=[('white', 'White'), ('black', 'Black'), ('grey', 'Grey'), ('bronze', 'Bronze'), ('champagne', 'Champagne'), ('wood_grain_oak', 'Wood Grain (Oak)'), ('wood_grain_teak', 'Wood Grain (Teak)'), ('custom_ral', 'Custom RAL Color')], default='white', max_length=20)),
                ('mesh_required', models.BooleanField(default=False)),
                ('mesh_type', models.CharField(choices=[('none', 'None'), ('fiberglass', 'Fiberglass'), ('stainless_steel', 'Stainless Steel')], default='none', max_length=20)),
                ('quantity', models.IntegerField(default=1, help_text='Number of units to fabricate')),
                ('typology_config', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('quoted', 'Quoted'), ('approved', 'Approved'), ('in_production', 'In Production'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('calculation_data', models.JSONField(blank=True, default=dict, help_text='Cached calculation results')),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Customer notes or comments')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Design',
                'verbose_name_plural': 'Designs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DesignRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changes', models.JSONField(default=dict, help_text='Fields that changed with old/new values')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='designs.windowdoordesign')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
