# Generated by Django 5.2.13 on 2026-04-29 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuttingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applies_to_type', models.CharField(choices=[('sliding_window', 'Sliding Window'), ('casement_window', 'Casement Window'), ('fixed_window', 'Fixed Window'), ('sliding_door', 'Sliding Door'), ('casement_door', 'Casement Door'), ('french_door', 'French Door'), ('bi_fold_door', 'Bi-fold Door'), ('tilt_turn', 'Tilt & Turn')], max_length=20)),
                ('description', models.CharField(help_text="e.g. 'Frame Top Rail', 'Sash Left Stile'", max_length=200)),
                ('formula', models.JSONField(default=dict, help_text='Calculation formula, e.g. {"base": "width", "subtract": 120, "add": 0}')),
                ('quantity_per_unit', models.IntegerField(default=1, help_text='Number of this piece per window/door unit')),
                ('cut_angle', models.CharField(choices=[('90deg', '90°'), ('45deg', '45°')], default='90deg', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutting_rules', to='materials.profiledatabase')),
            ],
            options={
                'verbose_name': 'Cutting Rule',
                'verbose_name_plural': 'Cutting Rules',
                'ordering': ['applies_to_type', 'sort_order'],
            },
        ),
    ]
