# Generated by Django 5.2.13 on 2026-04-29 19:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlassType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('clear_float', 'Clear Float'), ('tinted', 'Tinted'), ('frosted', 'Frosted'), ('tempered', 'Tempered'), ('double_glazed', 'Double Glazed'), ('laminated', 'Laminated'), ('reflective', 'Reflective')], max_length=20, unique=True)),
                ('thickness_mm', models.IntegerField(default=5)),
                ('price_per_sqm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Glass Type',
                'verbose_name_plural': 'Glass Types',
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='HardwareItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('handle', 'Handle'), ('lock', 'Lock'), ('hinge', 'Hinge'), ('roller', 'Roller'), ('seal', 'Seal / Gasket'), ('screw_pack', 'Screw Pack'), ('weather_strip', 'Weather Strip'), ('restrictor', 'Restrictor'), ('mosquito_mesh', 'Mosquito Mesh Kit')], max_length=20)),
                ('unit', models.CharField(choices=[('piece', 'Piece'), ('set', 'Set'), ('meter', 'Meter'), ('pack', 'Pack')], default='piece', max_length=10)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('applies_to_types', models.JSONField(default=list, help_text='List of window/door types this hardware applies to')),
                ('quantity_formula', models.CharField(blank=True, help_text="e.g. '2_per_sash', '1_per_unit', 'perimeter_m'", max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hardware Item',
                'verbose_name_plural': 'Hardware Items',
                'ordering': ['category', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ProfileDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_code', models.CharField(max_length=50, unique=True)),
                ('profile_name', models.CharField(max_length=200)),
                ('profile_type', models.CharField(choices=[('frame', 'Frame'), ('sash', 'Sash'), ('mullion', 'Mullion'), ('transom', 'Transom'), ('bead', 'Bead / Glazing Bead'), ('threshold', 'Threshold'), ('adapter', 'Adapter'), ('interlock', 'Interlock'), ('track', 'Track')], max_length=20)),
                ('material', models.CharField(choices=[('upvc', 'uPVC'), ('aluminium_standard', 'Aluminium (Standard)'), ('aluminium_thermal_break', 'Aluminium (Thermal Break)'), ('wood_composite', 'Wood Composite')], default='upvc', max_length=30)),
                ('standard_bar_length_mm', models.IntegerField(default=6000, help_text='Standard bar length in mm')),
                ('weight_per_meter_kg', models.DecimalField(decimal_places=3, default=Decimal('0.500'), max_digits=8)),
                ('cost_per_meter', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('cutting_waste_factor', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Waste factor percentage', max_digits=5)),
                ('wall_thickness_mm', models.IntegerField(default=60, help_text='Profile wall/depth thickness in mm')),
                ('rebate_depth_mm', models.IntegerField(default=18, help_text='Rebate depth for glass seating in mm')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'ordering': ['profile_type', 'profile_code'],
            },
        ),
    ]
