# Generated by Django 5.2.13 on 2026-04-29 19:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Pricing', max_length=100)),
                ('profile_markup_percent', models.DecimalField(decimal_places=2, default=Decimal('25.00'), help_text='Markup on profile material costs', max_digits=5)),
                ('glass_markup_percent', models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Markup on glass costs', max_digits=5)),
                ('hardware_markup_percent', models.DecimalField(decimal_places=2, default=Decimal('30.00'), help_text='Markup on hardware costs', max_digits=5)),
                ('labour_cost_per_unit', models.DecimalField(decimal_places=2, default=Decimal('500.00'), help_text='Labour cost per window/door unit', max_digits=10)),
                ('overhead_percent', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Overhead percentage on total cost', max_digits=5)),
                ('tax_rate_percent', models.DecimalField(decimal_places=2, default=Decimal('18.00'), help_text='Tax rate (e.g. GST)', max_digits=5)),
                ('currency_symbol', models.CharField(default='₹', max_length=10)),
                ('currency_code', models.CharField(default='INR', max_length=5)),
                ('saw_kerf_mm', models.IntegerField(default=3, help_text='Saw blade kerf in mm')),
                ('clearance_gap_mm', models.IntegerField(default=4, help_text='Glass clearance gap in mm')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pricing Configuration',
                'verbose_name_plural': 'Pricing Configurations',
            },
        ),
    ]
